import streamlit as st
import json
from openai import OpenAI
from pypdf import PdfReader
from fpdf import FPDF, HTMLMixin

# 1. Page Config
st.set_page_config(page_title="Salesforce Resume Architect", page_icon="☁️", layout="wide")

# 2. API Setup
api_key = st.secrets.get("OPENAI_API_KEY")
if not api_key:
    st.error("🚨 API Key Missing. Please check Streamlit Secrets.")
    st.stop()

client = OpenAI(api_key=api_key)

# 3. Define the PDF Generator (Pure Python)
class PDF(FPDF, HTMLMixin):
    def header(self):
        # Optional: Add a logo or header line here
        self.set_font("Helvetica", 'B', 10)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "Generated by AI Salesforce Architect", align="R")
        self.ln(15)

# 4. Logic Functions
def analyze_gap(resume_text, jd_text):
    """
    Finds the missing skills.
    """
    prompt = f"""
    You are a Salesforce Architect Recruiter. 
    Analyze the RESUME vs JOB DESCRIPTION.
    
    Return purely JSON:
    {{
        "score": 0,
        "missing_keywords": ["list", "of", "words"],
        "summary": "One sentence summary."
    }}
    
    RESUME: {resume_text[:3000]}
    JD: {jd_text[:3000]}
    """
    response = client.chat.completions.create(
        model="gpt-4o-mini", # Cheap model for analysis
        messages=[{"role": "user", "content": prompt}],
        response_format={"type": "json_object"}
    )
    return json.loads(response.choices[0].message.content)

def generate_optimized_content(resume_text, jd_text, gap_data):
    """
    Rewrites the resume using FPDF2-compatible HTML.
    """
    prompt = f"""
    Rewrite this resume to target the Job Description.
    Integrate these missing keywords: {gap_data['missing_keywords']}
    
    IMPORTANT FORMATTING RULES:
    1. Return ONLY valid HTML.
    2. Use ONLY these tags: <h1>, <h3>, <b>, <i>, <ul>, <li>, <br>, <p>.
    3. Do NOT use CSS, <style>, <div>, or <span>. FPDF2 does not support them.
    4. Structure:
       <h1 align="center">CANDIDATE NAME</h1>
       <p align="center">City, State | email@example.com | LinkedIn</p>
       
       <h3>PROFESSIONAL SUMMARY</h3>
       <p>...summary...</p>
       
       <h3>TECHNICAL SKILLS</h3>
       <p><b>Salesforce:</b> ...skills...</p>
       
       <h3>EXPERIENCE</h3>
       <b>Role Title</b> - Company<br>
       <i>Date - Date</i>
       <ul>
         <li>Bullet point using STAR method...</li>
       </ul>

    RESUME: {resume_text[:3000]}
    JD: {jd_text[:3000]}
    """
    
    response = client.chat.completions.create(
        model="gpt-4o", # Smart model for writing
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content

# 5. UI Layout
st.title("☁️ Salesforce Resume Architect")
st.markdown("Upload your resume and a JD. We will analyze gaps and **rewrite** your resume.")

# Inputs
col1, col2 = st.columns(2)
with col1:
    jd_input = st.text_area("Job Description", height=200)
with col2:
    uploaded_file = st.file_uploader("Upload Resume (PDF)", type="pdf")

# Processing
if st.button("Analyze & Rewrite"):
    if not jd_input or not uploaded_file:
        st.warning("⚠️ Please provide both a JD and a PDF.")
    else:
        # Read
        reader = PdfReader(uploaded_file)
        text = "".join([page.extract_text() for page in reader.pages])
        
        # Analyze
        with st.spinner("Analyzing Gaps..."):
            analysis = analyze_gap(text, jd_input)
            
        # Rewrite
        with st.spinner("Rewriting Resume (This takes about 15s)..."):
            new_html = generate_optimized_content(text, jd_input, analysis)
            
        # Generate PDF
        try:
            pdf = PDF()
            pdf.add_page()
            pdf.write_html(new_html)
            pdf_data = pdf.output(dest='S') # S = return as string/bytes
        except Exception as e:
            st.error(f"PDF Generation Error: {e}")
            st.stop()

        # Display Results
        st.divider()
        st.subheader("🎉 Results")
        
        # Metrics
        c1, c2, c3 = st.columns(3)
        with c1:
            st.metric("Match Score", f"{analysis['score']}%")
        with c2:
            st.write("**Missing Keywords:**")
            st.write(", ".join(analysis['missing_keywords']))
        with c3:
            st.download_button(
                label="📥 Download New Resume",
                data=pdf_data,
                file_name="Optimized_Salesforce_Resume.pdf",
                mime="application/pdf"
            )
            
        # Preview
        with st.expander("Preview Resume Text"):
            st.html(new_html) # This renders the HTML in the browser so you can see it
